// Service worker entry. Behavior lives in offline-kit; esbuild bundles it
// into sw.js at build time and injects __SW_MANIFEST (the precache list,
// generated by globbing + hashing the built assets). The /// reference pulls in
// the package's ambient type for that injected global, so there's no hand-rolled
// `declare const` to drift from the build's define.

/// <reference types="@tklepzig/offline-kit/global" />
import { createOfflineServiceWorker } from "@tklepzig/offline-kit/sw";

createOfflineServiceWorker({
  cacheName: "trica-cache",
  precache: __SW_MANIFEST,
});
